name: GitHub Actions Demo
on:
  pull_request:
    types: [opened, reopened]
jobs:
  Pull-Request-Opened:
    runs-on: ubuntu-latest
    steps:
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."